name: Trek Title Card Bot

on:
  schedule:
    # This runs at minute 13 of every hour
    - cron: '13 * * * *'
  workflow_dispatch: # This allows you to also run it manually whenever you want

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install atproto Pillow
      - name: Run bot
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
        run: python bot.py
        
